### ISSUE TITLE
it's not linting at all

### ISSUE THREAD

**Issue by craigcosmo** [azeemba/eslint-plugin-json#10]
I got json like this
```
{
   "text": "a thing"
   "user": "11"
}
```
Then I type lint command, it runs , but no error. I was expecting error missing comma

**Comment by azeemba** [comment]
I see the following error:
```
... testlint/test.json
  3:9  error  Expected '}' and instead saw 'user'        bad-json
  3:9  error  Unrecoverable syntax error. (60% scanned)  bad-json
```

Are you sure you added the plugin in your `.eslintrc` file? Are you running the command with `--ext` command?

**Comment by craigcosmo** [comment]
I added it to plugin.

This is my package.json command

```json
"lint": "eslint . --ext .json app "
```

app this folder where I put my code

**Comment by craigcosmo** [comment]
weird it's working now
