### ISSUE TITLE
Error on the first colon.

### ISSUE THREAD

**Issue by richardpringle** [azeemba/eslint-plugin-json#14]
eslint version: v3.19.0

```bash
$ eslint file.json
  1:7  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)
```

Where the json is as follows:
```json
{"key": "value"}
```

**Comment by richardpringle** [comment]
@azeemba, let me know if you need any help reproducing the issue

**Comment by azeemba** [comment]
Please have a look at the Usage info at https://github.com/azeemba/eslint-plugin-json#usage

I can reproduce your error when I don't add `json` to the plugins list.

**Comment by richardpringle** [comment]
@azeemba, I read the usage properly. 

I discovered the issue was with my install path for the plugin. Thanks for responding!
