### ISSUE TITLE
Ability to customize JSHint rules

### ISSUE THREAD

**Issue by chrisgarrity** [azeemba/eslint-plugin-json#15]
Everything from JSHint, including warnings, gets treated as an error by eslint. It would be great to be able to turn off certain rules.

For example, I'm trying to lint json files that contain locale data. There are warnings `This character may get silently deleted by one or more browsers` for languages that include diacritical marks (combined characters). Given the browsers we target, this is not something that I want as a failure, however - everything from the plugin is treated as a failure by eslint. I added a .jshintrcfile, but it's ignored by the plugin.

Is there already a way to do this that I missed?

**Comment by azeemba** [comment]
I am sorry for the late response. Previously the JSHint interface wasn't flexible enough for many options.

Now that we have switched to a different implementation, adding new plugin options should be feasible. Let me know if you still see your specific issue in v1.3.1 and we can discuss adding an option for that.

**Comment by chrisgarrity** [comment]
Thanks for the update. I ended up just using jshint directly instead of as a plugin. When I have time, I'll look into using it as a plugin again.

**Comment by azeemba** [comment]
As discussed in #21, it seems that eslint doesn't support processor plugins to add their own rules. I have created a new issue with eslint to investigate.

In the meanwhile I will close this issue. Once we have a good solution on adding options, I will start investigating again.
