### ISSUE TITLE
jshint vulnerability

### ISSUE THREAD

**Issue by imarotte** [azeemba/eslint-plugin-json#16]
npm audit revealed a vulnerability.  eslint-plugin-json is using an outdated version of jshint

Dependency of   eslint-plugin-json                                            
                                                                                
  Path            eslint-plugin-json > jshint > lodash                          
                                                                                
  More info       https://nodesecurity.io/advisories/577

**Comment by azeemba** [comment]
Thanks @imarotte! Looks like jshint hasn't released and upgraded version. Once it is, I will make sure to update the dependency here.

Here is the issue for reference: https://github.com/jshint/jshint/issues/3257

**Comment by doasync** [comment]
![screenshot from 2018-07-16 00-38-51](https://user-images.githubusercontent.com/29141708/42738711-dcf7cfb2-8890-11e8-8817-3cbefce2c14b.png)

**Comment by azeemba** [comment]
Still waiting on jshint/jshint#3257

**Comment by azeemba** [comment]
This was fixed in #18 by @thethomaseffect!
I just released the latest version (1.2.1) a few minutes ago and it looks good!

Thanks for reporting the issue and thanks for the PR with the fix!
