### ISSUE TITLE
ESLint Rules

### ISSUE THREAD

**Issue by ddavtian** [azeemba/eslint-plugin-json#17]
Hello,

Apologies in advance if this is a question that has been asked before. Using this plugin is it possible to still load the rules for ESLint? My goal is to turn off the error reporting on duplicate keys

```
{
    "env": {
        "browser": true
    },
    "extends": "eslint:recommended",
    "plugins": [
        "json"
    ],
    "rules": {
        "no-dupe-keys": "off"
    }
}
```

It didn't seem to work because the output shows

```
eslint . --ext .json

403:9  error  Duplicate key 'groupName'  bad-json
404:9  error  Duplicate key 'resources'  bad-json
```

**Comment by ddavtian** [comment]
Ok after spending some time I realized the loading `.eslintrc` is not going to be an option, but is there a way to say turn on/off some rules? Thank you for your time.

**Comment by azeemba** [comment]
The current implementation does not support any way of disabling rules.
