### ISSUE TITLE
JSON files are ignored by default

### ISSUE THREAD

**Issue by cdfa** [azeemba/eslint-plugin-json#23]
It seems `eslint` ignores `.json` files by default. It would be helpful if the installation instruction said how to unignore them with a `.eslintignore`

**Comment by AdrieanKhisbe** [comment]
Hey @cdfa 
What you describe is a behavior from eslint which only lint `.js` files unless you specify extensions via `--ext .xx`

Documentation has been added there:
https://github.com/azeemba/eslint-plugin-json#basic-configuration

Is it good for you?

**Comment by cdfa** [comment]
Yup, seems good!
