### ISSUE TITLE
2.0.0 unpublished

### ISSUE THREAD

**Issue by Cherry** [azeemba/eslint-plugin-json#28]
It appears that 2.0.0 was unpublished. 

I understand that 2.0.0 had issues as per #27, but unpublishing is going to cause even more issues for the numerous projects that received a PR this morning to update, and merged because it caused no issues with their CI.

See https://github.com/pulls?q=is%3Apr+%22eslint-plugin-json+to+the+latest+version%22 for example (just for greenkeeper), or my own repo at https://github.com/Cherry/report-to/pull/9.

**Comment by AdrieanKhisbe** [comment]
Damn, that reminds me why I really hate greenkeeper 😑 
Will try to make changes work working v2 (cf #27 ) quickly

**Comment by azeemba** [comment]
Apologies for the inconvenience. I unpublished within minutes but didn't anticipate automated tools picking the version up. Making things worse, I am unable to release to 2.0.0 again nor am I able to "reinstate" the previously published version. 

I have published 2.0.1 version and hopefully the same automated tools will pick it up and apply that.

**Comment by Cherry** [comment]
Thanks for the quick resolution all. 👍
