### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [azeemba/eslint-plugin-json#44]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

**Comment by AdrieanKhisbe** [comment]
Thanks for your help proposal @MichaelDeBoey 🙂 

`eslint-plugin-json` already support `eslint` 7.x out of the box,
so I think we can close the issue.

Also with #46 having land, we ensure that future changes are working with eslint 6.x and 7.x major lines.

There is no reason at the moment to set eslint as peerDependencies with 7 as minimal version as proposed in #43.

**Comment by MichaelDeBoey** [comment]
Closed by #46
