### ISSUE TITLE
Is it possible to use this plugin/parser to make our own custom rules?

### ISSUE THREAD

**Issue by 0xdevalias** [azeemba/eslint-plugin-json#55]
I'm not sure if it is currently possible, but it would be awesome if we were able to use this plugin as a parser for implementing our own custom json-based rules.

- https://eslint.org/docs/user-guide/configuring#specifying-parser
- https://eslint.org/docs/developer-guide/working-with-custom-parsers

When googling, there is another project that is supposedly an eslint json parser, but it is built on [eslint/espree](https://github.com/eslint/espree), so may have the [issues mentioned in your readme](https://github.com/azeemba/eslint-plugin-json#why-doesnt-this-plugin-use-eslint-itself-or-just-jsonparse)

- https://github.com/zeitport/eslint-parser-json

**Comment by azeemba** [comment]
Hey thanks for the question. This extension doesn't expose the parser but looks like the [module](https://github.com/microsoft/vscode-json-languageservice) used could potentially allow for it to be exposed.

I am not really familiar with how custom parsers work for eslint so if someone is interested in implementing this in a backwards compatible way, then I would be open to that. If someone is interested, it is probably best to first describe and discuss the suggested change.

**Comment by azeemba** [comment]
Thanks for linking https://github.com/zeitport/eslint-parser-json

I had a look through and it looks awesome! I will go ahead and close this issue since I think that project seems to fit your use-case well.
