### ISSUE TITLE
Minimatch deprecation warning

### ISSUE THREAD

**Issue by jksmilton** [azeemba/eslint-plugin-json#6]
Need to bump the version of JSHint used to one that has updated its version of minimatch to at least 3.0.2.

**Comment by azeemba** [comment]
Looks like the latest release of jshint/jshint (2.9.2) still has the issue (though master seems to have it fixed). So I guess have to wait for the next release.

Thanks for the report though!

**Comment by azeemba** [comment]
Has been fixed per jshint/jshint#2952
