### ISSUE TITLE
Version problems with npm

### ISSUE THREAD

**Issue by MansurAliKoroglu** [azeemba/eslint-plugin-json#66]
In master branch version is currently `3.0.0`. In releases there is `v3.0.0` tag. However, in npm the latest version is `3.1.0`. There is no `v3.1.0` tag in here. What's wrong?

**Comment by azeemba** [comment]
Sorry about that. The released only contained dependency updates with no other code changes.

I missed pushing the version bump commit and tag. Thanks for reporting this! It has been fixed now.

**Comment by MansurAliKoroglu** [comment]
btw, in the releases github stills shows a very old version as latest.

![image](https://user-images.githubusercontent.com/43291306/129435051-45b3acd2-782c-49af-be2f-f6348a50a4b1.png)
