### ISSUE TITLE
Line 1 always fails with error

### ISSUE THREAD

**Issue by miloman** [azeemba/eslint-plugin-json#74]
I get the following error for every json file, including package.json.

1:1  error  Expected an assignment or function call and instead saw an expression  no-unused-expressions

I am able to by-pass this error by adding the following line to the top of each file, but I would prefer to understand what the error is or how to suppress it completely

// eslint-disable-next-line no-unused-expressions

**Comment by azeemba** [comment]
That error is coming from eslint itself. Based on your config, eslint is treating that file as a JavaScript file (not as JSON).
