### ISSUE TITLE
Support flat config

### ISSUE THREAD

**Issue by sdavids** [azeemba/eslint-plugin-json#80]
https://eslint.org/blog/2023/10/flat-config-rollout-plans/

**Comment by 4a-ge** [comment]
But it works with flat config, doesn't it?

```
const json = require('eslint-plugin-json');

module.exports = [
  {
    files: ['**/*.json'],
    plugins: { json },
    processor: json.processors['.json'],
    rules: json.configs.recommended.rules,
  },
]
```

**Comment by Standard8** [comment]
It looks like it will work that way, but it the plug-in can also be migrated to support flag configuration better:

https://eslint.org/docs/latest/extend/plugin-migration-flat-config

(it can also support both new & old).

**Comment by sdavids** [comment]
Also, update README with flat config examples.

**Comment by BePo65** [comment]
in Eslint v9 the work-around of @4a-ge does not work any more. I used
```javascript
import globals from "globals";
import pluginJs from "@eslint/js";
import pluginJson from "eslint-plugin-json";

export default [
  pluginJs.configs.recommended,
  pluginJson.configs.recommended,
  {
    files: [ '**/*.js' ],
    languageOptions: {
      globals: globals.nodeBuiltin,
    },
    rules: {
    },
  },
  {
    files: [ '**/*.json' ],
    plugins: {
      pluginJson,
    },
    processor: pluginJson.processors['.json'],
    rules: {
      ...pluginJson.configs.recommended.rules
    },
  }
];
```

and got
```
Oops! Something went wrong! :(

ESLint: 9.1.1


A config object has a "plugins" key defined as an array of strings.

Flat config requires "plugins" to be an object in this form:
    {
        plugins: {
            json: pluginObject
        }
    }

Please see the following page for information on how to convert your config object into the correct format:
https://eslint.org/docs/latest/use/configure/migration-guide#importing-plugins-and-custom-parsers

If you're using a shareable config that you cannot rewrite in flat config format, then use the compatibility utility:
https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config
```

**Comment by Standard8** [comment]
> in Eslint v9 the work-around of @4a-ge does not work unchanged - the recommended ruleset throws. I used
> 
...
> ```js
> export default [
>   pluginJs.configs.recommended,
>   pluginJson.configs.recommended,
> ```

This is incorrect you're trying to include the whole recommended configuration, whereas you want to only include `.rules` as you attempted to below:

> ```js
>   {
>     files: [ '**/*.json' ],
>     plugins: {
>       pluginJson,
>     },
>     processor: pluginJson.processors['.json'],
>     rules: {
>       ...pluginJson.configs.recommended.rules
>     },
> ];
> ```

I suspect if you took out those first two lines it would work fine.
